/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const DetectionResult = IDL.Record({
  'id' : IDL.Text,
  'environmentalConditions' : IDL.Record({
    'roadType' : IDL.Text,
    'surfaceType' : IDL.Text,
    'lighting' : IDL.Text,
    'weather' : IDL.Text,
  }),
  'metrics' : IDL.Record({
    'objectDetection' : IDL.Text,
    'systemPerformance' : IDL.Record({
      'cpuUtilization' : IDL.Float64,
      'gpuUtilization' : IDL.Float64,
      'memoryUsage' : IDL.Float64,
      'hardwareType' : IDL.Text,
    }),
    'detectionQuality' : IDL.Float64,
    'frameRate' : IDL.Float64,
  }),
  'processingTime' : IDL.Nat,
  'confidenceScore' : IDL.Float64,
  'processedImage' : ExternalBlob,
  'timestamp' : Time,
  'image' : ExternalBlob,
});
export const EmergencyEvent = IDL.Record({
  'id' : IDL.Text,
  'type' : IDL.Text,
  'resolutionStatus' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
  'associatedDetectionId' : IDL.Text,
  'severity' : IDL.Record({ 'urgency' : IDL.Text, 'level' : IDL.Text }),
});
export const HardwarePerformanceMetrics = IDL.Record({
  'optimizationLevel' : IDL.Text,
  'processingEfficiency' : IDL.Float64,
  'cpuUtilization' : IDL.Float64,
  'gpuUtilization' : IDL.Float64,
  'memoryUsage' : IDL.Float64,
  'benchmarkScores' : IDL.Record({
    'gpuScore' : IDL.Float64,
    'cpuScore' : IDL.Float64,
  }),
  'hardwareType' : IDL.Text,
});
export const ObstacleEvent = IDL.Record({
  'id' : IDL.Text,
  'type' : IDL.Text,
  'confidenceLevel' : IDL.Float64,
  'timestamp' : Time,
  'associatedDetectionId' : IDL.Text,
  'image' : ExternalBlob,
  'position' : IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 }),
  'riskLevel' : IDL.Record({ 'description' : IDL.Text, 'level' : IDL.Text }),
});
export const SpecificationReportResponse = IDL.Record({
  'id' : IDL.Text,
  'content' : ExternalBlob,
  'createdAt' : Time,
});
export const SpeedLimitDetection = IDL.Record({
  'id' : IDL.Text,
  'frameData' : ExternalBlob,
  'confidenceLevel' : IDL.Float64,
  'timestamp' : Time,
  'detectedSpeedLimit' : IDL.Opt(IDL.Nat),
  'associatedDetectionId' : IDL.Text,
});
export const VideoProcessingStatusRequest = IDL.Record({ 'taskId' : IDL.Text });
export const VideoProcessingStatusResponse = IDL.Record({});
export const VideoUploadRequest = IDL.Record({ 'videoBlob' : ExternalBlob });
export const VideoUploadResponse = IDL.Record({ 'taskId' : IDL.Text });
export const CameraStatusRequest = IDL.Record({ 'state' : IDL.Text });
export const CameraStatusResponse = IDL.Record({ 'message' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'getAllDetectionResults' : IDL.Func(
      [],
      [IDL.Vec(DetectionResult)],
      ['query'],
    ),
  'getAllEmergencyEvents' : IDL.Func([], [IDL.Vec(EmergencyEvent)], ['query']),
  'getAllHardwarePerformanceMetrics' : IDL.Func(
      [],
      [IDL.Vec(HardwarePerformanceMetrics)],
      ['query'],
    ),
  'getAllObstacleEvents' : IDL.Func([], [IDL.Vec(ObstacleEvent)], ['query']),
  'getAllSpecificationReports' : IDL.Func(
      [],
      [IDL.Vec(SpecificationReportResponse)],
      ['query'],
    ),
  'getAllSpeedLimitDetections' : IDL.Func(
      [],
      [IDL.Vec(SpeedLimitDetection)],
      ['query'],
    ),
  'getCombinedAlertHistory' : IDL.Func(
      [],
      [
        IDL.Record({
          'detectionResults' : IDL.Vec(DetectionResult),
          'speedLimitDetections' : IDL.Vec(SpeedLimitDetection),
          'emergencyEvents' : IDL.Vec(EmergencyEvent),
          'hardwarePerformanceMetrics' : IDL.Vec(HardwarePerformanceMetrics),
          'obstacleEvents' : IDL.Vec(ObstacleEvent),
        }),
      ],
      ['query'],
    ),
  'getDetectionResult' : IDL.Func([IDL.Text], [DetectionResult], ['query']),
  'getDetectionStatistics' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalDetections' : IDL.Nat,
          'totalHighRiskEvents' : IDL.Nat,
          'averageDetectionTime' : IDL.Float64,
          'highestRiskLevel' : IDL.Text,
          'totalSpeedLimitDetections' : IDL.Nat,
          'totalEmergencyEvents' : IDL.Nat,
          'mostCommonObjectType' : IDL.Text,
          'totalObstacleEvents' : IDL.Nat,
          'averageConfidenceScore' : IDL.Float64,
          'averageHardwareEfficiency' : IDL.Float64,
          'averageSpeedLimitConfidence' : IDL.Float64,
          'averageProcessingTime' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getEmergencyEvent' : IDL.Func([IDL.Text], [EmergencyEvent], ['query']),
  'getEnvironmentalAnalysis' : IDL.Func(
      [],
      [
        IDL.Record({
          'detectionScoreByCondition' : IDL.Record({
            'surfaceQuality' : IDL.Text,
            'avgScore' : IDL.Float64,
            'commonRoadType' : IDL.Text,
            'lighting' : IDL.Text,
            'weather' : IDL.Text,
          }),
        }),
      ],
      ['query'],
    ),
  'getFilteredAlertHistory' : IDL.Func(
      [
        IDL.Record({
          'detectionRange' : IDL.Opt(IDL.Float64),
          'weatherCondition' : IDL.Opt(IDL.Text),
          'timeRange' : IDL.Opt(IDL.Record({ 'end' : Time, 'start' : Time })),
          'severity' : IDL.Opt(IDL.Text),
          'speedLimitRange' : IDL.Opt(
            IDL.Record({ 'lower' : IDL.Nat, 'upper' : IDL.Nat })
          ),
          'objectType' : IDL.Opt(IDL.Text),
          'riskLevel' : IDL.Opt(IDL.Text),
        }),
      ],
      [
        IDL.Record({
          'detectionResults' : IDL.Vec(DetectionResult),
          'speedLimitDetections' : IDL.Vec(SpeedLimitDetection),
          'emergencyEvents' : IDL.Vec(EmergencyEvent),
          'obstacleEvents' : IDL.Vec(ObstacleEvent),
        }),
      ],
      ['query'],
    ),
  'getFilteredEventHistory' : IDL.Func(
      [
        IDL.Record({
          'detectionRange' : IDL.Opt(IDL.Float64),
          'severity' : IDL.Opt(IDL.Text),
          'objectType' : IDL.Opt(IDL.Text),
          'riskLevel' : IDL.Opt(IDL.Text),
        }),
      ],
      [
        IDL.Record({
          'emergencyEvents' : IDL.Vec(EmergencyEvent),
          'obstacleEvents' : IDL.Vec(ObstacleEvent),
        }),
      ],
      ['query'],
    ),
  'getHardwarePerformanceMetrics' : IDL.Func(
      [IDL.Text],
      [HardwarePerformanceMetrics],
      ['query'],
    ),
  'getObstacleEvent' : IDL.Func([IDL.Text], [ObstacleEvent], ['query']),
  'getSpecificationReport' : IDL.Func(
      [IDL.Text],
      [SpecificationReportResponse],
      ['query'],
    ),
  'getSpeedLimitDetection' : IDL.Func(
      [IDL.Text],
      [SpeedLimitDetection],
      ['query'],
    ),
  'getVideoProcessingStatus' : IDL.Func(
      [VideoProcessingStatusRequest],
      [VideoProcessingStatusResponse],
      [],
    ),
  'handleVideoUpload' : IDL.Func(
      [VideoUploadRequest],
      [VideoUploadResponse],
      [],
    ),
  'storeDetectionResult' : IDL.Func(
      [
        IDL.Text,
        ExternalBlob,
        ExternalBlob,
        IDL.Float64,
        IDL.Nat,
        Time,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'storeEmergencyEvent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Time,
        IDL.Text,
        IDL.Text,
        IDL.Record({ 'urgency' : IDL.Text, 'level' : IDL.Text }),
        IDL.Text,
      ],
      [],
      [],
    ),
  'storeHardwarePerformanceMetrics' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'storeObstacleEvent' : IDL.Func(
      [
        IDL.Text,
        IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 }),
        IDL.Text,
        IDL.Float64,
        Time,
        IDL.Text,
        ExternalBlob,
        IDL.Record({ 'description' : IDL.Text, 'level' : IDL.Text }),
      ],
      [],
      [],
    ),
  'storeSpecificationReport' : IDL.Func([IDL.Text, ExternalBlob, Time], [], []),
  'storeSpeedLimitDetection' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat), IDL.Float64, Time, IDL.Text, ExternalBlob],
      [],
      [],
    ),
  'updateCameraStatus' : IDL.Func(
      [CameraStatusRequest],
      [CameraStatusResponse],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const DetectionResult = IDL.Record({
    'id' : IDL.Text,
    'environmentalConditions' : IDL.Record({
      'roadType' : IDL.Text,
      'surfaceType' : IDL.Text,
      'lighting' : IDL.Text,
      'weather' : IDL.Text,
    }),
    'metrics' : IDL.Record({
      'objectDetection' : IDL.Text,
      'systemPerformance' : IDL.Record({
        'cpuUtilization' : IDL.Float64,
        'gpuUtilization' : IDL.Float64,
        'memoryUsage' : IDL.Float64,
        'hardwareType' : IDL.Text,
      }),
      'detectionQuality' : IDL.Float64,
      'frameRate' : IDL.Float64,
    }),
    'processingTime' : IDL.Nat,
    'confidenceScore' : IDL.Float64,
    'processedImage' : ExternalBlob,
    'timestamp' : Time,
    'image' : ExternalBlob,
  });
  const EmergencyEvent = IDL.Record({
    'id' : IDL.Text,
    'type' : IDL.Text,
    'resolutionStatus' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
    'associatedDetectionId' : IDL.Text,
    'severity' : IDL.Record({ 'urgency' : IDL.Text, 'level' : IDL.Text }),
  });
  const HardwarePerformanceMetrics = IDL.Record({
    'optimizationLevel' : IDL.Text,
    'processingEfficiency' : IDL.Float64,
    'cpuUtilization' : IDL.Float64,
    'gpuUtilization' : IDL.Float64,
    'memoryUsage' : IDL.Float64,
    'benchmarkScores' : IDL.Record({
      'gpuScore' : IDL.Float64,
      'cpuScore' : IDL.Float64,
    }),
    'hardwareType' : IDL.Text,
  });
  const ObstacleEvent = IDL.Record({
    'id' : IDL.Text,
    'type' : IDL.Text,
    'confidenceLevel' : IDL.Float64,
    'timestamp' : Time,
    'associatedDetectionId' : IDL.Text,
    'image' : ExternalBlob,
    'position' : IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 }),
    'riskLevel' : IDL.Record({ 'description' : IDL.Text, 'level' : IDL.Text }),
  });
  const SpecificationReportResponse = IDL.Record({
    'id' : IDL.Text,
    'content' : ExternalBlob,
    'createdAt' : Time,
  });
  const SpeedLimitDetection = IDL.Record({
    'id' : IDL.Text,
    'frameData' : ExternalBlob,
    'confidenceLevel' : IDL.Float64,
    'timestamp' : Time,
    'detectedSpeedLimit' : IDL.Opt(IDL.Nat),
    'associatedDetectionId' : IDL.Text,
  });
  const VideoProcessingStatusRequest = IDL.Record({ 'taskId' : IDL.Text });
  const VideoProcessingStatusResponse = IDL.Record({});
  const VideoUploadRequest = IDL.Record({ 'videoBlob' : ExternalBlob });
  const VideoUploadResponse = IDL.Record({ 'taskId' : IDL.Text });
  const CameraStatusRequest = IDL.Record({ 'state' : IDL.Text });
  const CameraStatusResponse = IDL.Record({ 'message' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'getAllDetectionResults' : IDL.Func(
        [],
        [IDL.Vec(DetectionResult)],
        ['query'],
      ),
    'getAllEmergencyEvents' : IDL.Func(
        [],
        [IDL.Vec(EmergencyEvent)],
        ['query'],
      ),
    'getAllHardwarePerformanceMetrics' : IDL.Func(
        [],
        [IDL.Vec(HardwarePerformanceMetrics)],
        ['query'],
      ),
    'getAllObstacleEvents' : IDL.Func([], [IDL.Vec(ObstacleEvent)], ['query']),
    'getAllSpecificationReports' : IDL.Func(
        [],
        [IDL.Vec(SpecificationReportResponse)],
        ['query'],
      ),
    'getAllSpeedLimitDetections' : IDL.Func(
        [],
        [IDL.Vec(SpeedLimitDetection)],
        ['query'],
      ),
    'getCombinedAlertHistory' : IDL.Func(
        [],
        [
          IDL.Record({
            'detectionResults' : IDL.Vec(DetectionResult),
            'speedLimitDetections' : IDL.Vec(SpeedLimitDetection),
            'emergencyEvents' : IDL.Vec(EmergencyEvent),
            'hardwarePerformanceMetrics' : IDL.Vec(HardwarePerformanceMetrics),
            'obstacleEvents' : IDL.Vec(ObstacleEvent),
          }),
        ],
        ['query'],
      ),
    'getDetectionResult' : IDL.Func([IDL.Text], [DetectionResult], ['query']),
    'getDetectionStatistics' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalDetections' : IDL.Nat,
            'totalHighRiskEvents' : IDL.Nat,
            'averageDetectionTime' : IDL.Float64,
            'highestRiskLevel' : IDL.Text,
            'totalSpeedLimitDetections' : IDL.Nat,
            'totalEmergencyEvents' : IDL.Nat,
            'mostCommonObjectType' : IDL.Text,
            'totalObstacleEvents' : IDL.Nat,
            'averageConfidenceScore' : IDL.Float64,
            'averageHardwareEfficiency' : IDL.Float64,
            'averageSpeedLimitConfidence' : IDL.Float64,
            'averageProcessingTime' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getEmergencyEvent' : IDL.Func([IDL.Text], [EmergencyEvent], ['query']),
    'getEnvironmentalAnalysis' : IDL.Func(
        [],
        [
          IDL.Record({
            'detectionScoreByCondition' : IDL.Record({
              'surfaceQuality' : IDL.Text,
              'avgScore' : IDL.Float64,
              'commonRoadType' : IDL.Text,
              'lighting' : IDL.Text,
              'weather' : IDL.Text,
            }),
          }),
        ],
        ['query'],
      ),
    'getFilteredAlertHistory' : IDL.Func(
        [
          IDL.Record({
            'detectionRange' : IDL.Opt(IDL.Float64),
            'weatherCondition' : IDL.Opt(IDL.Text),
            'timeRange' : IDL.Opt(IDL.Record({ 'end' : Time, 'start' : Time })),
            'severity' : IDL.Opt(IDL.Text),
            'speedLimitRange' : IDL.Opt(
              IDL.Record({ 'lower' : IDL.Nat, 'upper' : IDL.Nat })
            ),
            'objectType' : IDL.Opt(IDL.Text),
            'riskLevel' : IDL.Opt(IDL.Text),
          }),
        ],
        [
          IDL.Record({
            'detectionResults' : IDL.Vec(DetectionResult),
            'speedLimitDetections' : IDL.Vec(SpeedLimitDetection),
            'emergencyEvents' : IDL.Vec(EmergencyEvent),
            'obstacleEvents' : IDL.Vec(ObstacleEvent),
          }),
        ],
        ['query'],
      ),
    'getFilteredEventHistory' : IDL.Func(
        [
          IDL.Record({
            'detectionRange' : IDL.Opt(IDL.Float64),
            'severity' : IDL.Opt(IDL.Text),
            'objectType' : IDL.Opt(IDL.Text),
            'riskLevel' : IDL.Opt(IDL.Text),
          }),
        ],
        [
          IDL.Record({
            'emergencyEvents' : IDL.Vec(EmergencyEvent),
            'obstacleEvents' : IDL.Vec(ObstacleEvent),
          }),
        ],
        ['query'],
      ),
    'getHardwarePerformanceMetrics' : IDL.Func(
        [IDL.Text],
        [HardwarePerformanceMetrics],
        ['query'],
      ),
    'getObstacleEvent' : IDL.Func([IDL.Text], [ObstacleEvent], ['query']),
    'getSpecificationReport' : IDL.Func(
        [IDL.Text],
        [SpecificationReportResponse],
        ['query'],
      ),
    'getSpeedLimitDetection' : IDL.Func(
        [IDL.Text],
        [SpeedLimitDetection],
        ['query'],
      ),
    'getVideoProcessingStatus' : IDL.Func(
        [VideoProcessingStatusRequest],
        [VideoProcessingStatusResponse],
        [],
      ),
    'handleVideoUpload' : IDL.Func(
        [VideoUploadRequest],
        [VideoUploadResponse],
        [],
      ),
    'storeDetectionResult' : IDL.Func(
        [
          IDL.Text,
          ExternalBlob,
          ExternalBlob,
          IDL.Float64,
          IDL.Nat,
          Time,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'storeEmergencyEvent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Time,
          IDL.Text,
          IDL.Text,
          IDL.Record({ 'urgency' : IDL.Text, 'level' : IDL.Text }),
          IDL.Text,
        ],
        [],
        [],
      ),
    'storeHardwarePerformanceMetrics' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'storeObstacleEvent' : IDL.Func(
        [
          IDL.Text,
          IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 }),
          IDL.Text,
          IDL.Float64,
          Time,
          IDL.Text,
          ExternalBlob,
          IDL.Record({ 'description' : IDL.Text, 'level' : IDL.Text }),
        ],
        [],
        [],
      ),
    'storeSpecificationReport' : IDL.Func(
        [IDL.Text, ExternalBlob, Time],
        [],
        [],
      ),
    'storeSpeedLimitDetection' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), IDL.Float64, Time, IDL.Text, ExternalBlob],
        [],
        [],
      ),
    'updateCameraStatus' : IDL.Func(
        [CameraStatusRequest],
        [CameraStatusResponse],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };