/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CameraStatusRequest { 'state' : string }
export interface CameraStatusResponse { 'message' : string }
export interface DetectionResult {
  'id' : string,
  'environmentalConditions' : {
    'roadType' : string,
    'surfaceType' : string,
    'lighting' : string,
    'weather' : string,
  },
  'metrics' : {
    'objectDetection' : string,
    'systemPerformance' : {
      'cpuUtilization' : number,
      'gpuUtilization' : number,
      'memoryUsage' : number,
      'hardwareType' : string,
    },
    'detectionQuality' : number,
    'frameRate' : number,
  },
  'processingTime' : bigint,
  'confidenceScore' : number,
  'processedImage' : ExternalBlob,
  'timestamp' : Time,
  'image' : ExternalBlob,
}
export interface EmergencyEvent {
  'id' : string,
  'type' : string,
  'resolutionStatus' : string,
  'description' : string,
  'timestamp' : Time,
  'associatedDetectionId' : string,
  'severity' : { 'urgency' : string, 'level' : string },
}
export type ExternalBlob = Uint8Array;
export interface HardwarePerformanceMetrics {
  'optimizationLevel' : string,
  'processingEfficiency' : number,
  'cpuUtilization' : number,
  'gpuUtilization' : number,
  'memoryUsage' : number,
  'benchmarkScores' : { 'gpuScore' : number, 'cpuScore' : number },
  'hardwareType' : string,
}
export interface ObstacleEvent {
  'id' : string,
  'type' : string,
  'confidenceLevel' : number,
  'timestamp' : Time,
  'associatedDetectionId' : string,
  'image' : ExternalBlob,
  'position' : { 'x' : number, 'y' : number },
  'riskLevel' : { 'description' : string, 'level' : string },
}
export interface SpecificationReportResponse {
  'id' : string,
  'content' : ExternalBlob,
  'createdAt' : Time,
}
export interface SpeedLimitDetection {
  'id' : string,
  'frameData' : ExternalBlob,
  'confidenceLevel' : number,
  'timestamp' : Time,
  'detectedSpeedLimit' : [] | [bigint],
  'associatedDetectionId' : string,
}
export type Time = bigint;
export interface VideoProcessingStatusRequest { 'taskId' : string }
export type VideoProcessingStatusResponse = {};
export interface VideoUploadRequest { 'videoBlob' : ExternalBlob }
export interface VideoUploadResponse { 'taskId' : string }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'getAllDetectionResults' : ActorMethod<[], Array<DetectionResult>>,
  'getAllEmergencyEvents' : ActorMethod<[], Array<EmergencyEvent>>,
  'getAllHardwarePerformanceMetrics' : ActorMethod<
    [],
    Array<HardwarePerformanceMetrics>
  >,
  'getAllObstacleEvents' : ActorMethod<[], Array<ObstacleEvent>>,
  'getAllSpecificationReports' : ActorMethod<
    [],
    Array<SpecificationReportResponse>
  >,
  'getAllSpeedLimitDetections' : ActorMethod<[], Array<SpeedLimitDetection>>,
  'getCombinedAlertHistory' : ActorMethod<
    [],
    {
      'detectionResults' : Array<DetectionResult>,
      'speedLimitDetections' : Array<SpeedLimitDetection>,
      'emergencyEvents' : Array<EmergencyEvent>,
      'hardwarePerformanceMetrics' : Array<HardwarePerformanceMetrics>,
      'obstacleEvents' : Array<ObstacleEvent>,
    }
  >,
  'getDetectionResult' : ActorMethod<[string], DetectionResult>,
  'getDetectionStatistics' : ActorMethod<
    [],
    {
      'totalDetections' : bigint,
      'totalHighRiskEvents' : bigint,
      'averageDetectionTime' : number,
      'highestRiskLevel' : string,
      'totalSpeedLimitDetections' : bigint,
      'totalEmergencyEvents' : bigint,
      'mostCommonObjectType' : string,
      'totalObstacleEvents' : bigint,
      'averageConfidenceScore' : number,
      'averageHardwareEfficiency' : number,
      'averageSpeedLimitConfidence' : number,
      'averageProcessingTime' : number,
    }
  >,
  'getEmergencyEvent' : ActorMethod<[string], EmergencyEvent>,
  'getEnvironmentalAnalysis' : ActorMethod<
    [],
    {
      'detectionScoreByCondition' : {
        'surfaceQuality' : string,
        'avgScore' : number,
        'commonRoadType' : string,
        'lighting' : string,
        'weather' : string,
      },
    }
  >,
  'getFilteredAlertHistory' : ActorMethod<
    [
      {
        'detectionRange' : [] | [number],
        'weatherCondition' : [] | [string],
        'timeRange' : [] | [{ 'end' : Time, 'start' : Time }],
        'severity' : [] | [string],
        'speedLimitRange' : [] | [{ 'lower' : bigint, 'upper' : bigint }],
        'objectType' : [] | [string],
        'riskLevel' : [] | [string],
      },
    ],
    {
      'detectionResults' : Array<DetectionResult>,
      'speedLimitDetections' : Array<SpeedLimitDetection>,
      'emergencyEvents' : Array<EmergencyEvent>,
      'obstacleEvents' : Array<ObstacleEvent>,
    }
  >,
  'getFilteredEventHistory' : ActorMethod<
    [
      {
        'detectionRange' : [] | [number],
        'severity' : [] | [string],
        'objectType' : [] | [string],
        'riskLevel' : [] | [string],
      },
    ],
    {
      'emergencyEvents' : Array<EmergencyEvent>,
      'obstacleEvents' : Array<ObstacleEvent>,
    }
  >,
  'getHardwarePerformanceMetrics' : ActorMethod<
    [string],
    HardwarePerformanceMetrics
  >,
  'getObstacleEvent' : ActorMethod<[string], ObstacleEvent>,
  'getSpecificationReport' : ActorMethod<[string], SpecificationReportResponse>,
  'getSpeedLimitDetection' : ActorMethod<[string], SpeedLimitDetection>,
  'getVideoProcessingStatus' : ActorMethod<
    [VideoProcessingStatusRequest],
    VideoProcessingStatusResponse
  >,
  'handleVideoUpload' : ActorMethod<[VideoUploadRequest], VideoUploadResponse>,
  'storeDetectionResult' : ActorMethod<
    [
      string,
      ExternalBlob,
      ExternalBlob,
      number,
      bigint,
      Time,
      string,
      string,
      string,
      string,
      number,
      number,
      string,
      string,
      number,
      number,
      number,
    ],
    undefined
  >,
  'storeEmergencyEvent' : ActorMethod<
    [
      string,
      string,
      Time,
      string,
      string,
      { 'urgency' : string, 'level' : string },
      string,
    ],
    undefined
  >,
  'storeHardwarePerformanceMetrics' : ActorMethod<
    [string, string, number, number, number, number, number, string, number],
    undefined
  >,
  'storeObstacleEvent' : ActorMethod<
    [
      string,
      { 'x' : number, 'y' : number },
      string,
      number,
      Time,
      string,
      ExternalBlob,
      { 'description' : string, 'level' : string },
    ],
    undefined
  >,
  'storeSpecificationReport' : ActorMethod<
    [string, ExternalBlob, Time],
    undefined
  >,
  'storeSpeedLimitDetection' : ActorMethod<
    [string, [] | [bigint], number, Time, string, ExternalBlob],
    undefined
  >,
  'updateCameraStatus' : ActorMethod<
    [CameraStatusRequest],
    CameraStatusResponse
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];