/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccidentRecord {
  'id' : string,
  'description' : string,
  'timestamp' : Time,
  'location' : Location,
  'detectionMethod' : DetectionMethod,
  'analysisResults' : [] | [string],
  'images' : Array<ExternalBlob>,
}
export interface Classification {
  'motion' : MotionType,
  'objectType' : ObjectType,
}
export type DetectionMethod = { 'aiAnalyzed' : null } |
  { 'manual' : null };
export type ExternalBlob = Uint8Array;
export interface Location {
  'latitude' : number,
  'longitude' : number,
  'accuracy' : number,
}
export type MotionType = { 'static' : null } |
  { 'moving' : null };
export type ObjectType = { 'pedestrian' : null } |
  { 'debris' : null } |
  { 'vehicle' : null } |
  { 'unknown' : null };
export interface ObstacleEvent {
  'id' : string,
  'type' : string,
  'confidenceLevel' : number,
  'timestamp' : Time,
  'associatedDetectionId' : string,
  'image' : ExternalBlob,
  'position' : { 'x' : number, 'y' : number },
  'riskLevel' : { 'description' : string, 'level' : string },
  'potholeDetails' : [] | [PotholeDetails],
  'classification' : Classification,
}
export interface PotholeDetails {
  'potholeType' : PotholeType,
  'image_url' : string,
  'distance_from_vehicle' : number,
  'createdAt' : Time,
  'size' : number,
  'severity' : string,
  'depth' : number,
  'location' : { 'coordinates' : [number, number], 'accuracy' : number },
}
export type PotholeType = { 'deep' : null } |
  { 'edge' : null } |
  { 'pavement' : null } |
  { 'complex' : null } |
  { 'rough_size' : null } |
  { 'surface_cracks' : null } |
  { 'unknown' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAccidentRecord' : ActorMethod<
    [
      string,
      DetectionMethod,
      Location,
      Time,
      Array<ExternalBlob>,
      string,
      [] | [string],
    ],
    undefined
  >,
  'addPotholeSpecificEvent' : ActorMethod<
    [
      string,
      { 'x' : number, 'y' : number },
      number,
      Time,
      string,
      ExternalBlob,
      { 'description' : string, 'level' : string },
      PotholeDetails,
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAccidentRecord' : ActorMethod<[string], AccidentRecord>,
  'getAllAccidentRecords' : ActorMethod<[], Array<AccidentRecord>>,
  'getAllObstacleEvents' : ActorMethod<[], Array<ObstacleEvent>>,
  'getAllPotholeEvents' : ActorMethod<[], Array<ObstacleEvent>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getObstacleEvent' : ActorMethod<[string], ObstacleEvent>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'storeObstacleEvent' : ActorMethod<
    [
      string,
      { 'x' : number, 'y' : number },
      string,
      number,
      Time,
      string,
      ExternalBlob,
      { 'description' : string, 'level' : string },
      Classification,
      [] | [PotholeDetails],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];