/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const DetectionMethod = IDL.Variant({
  'aiAnalyzed' : IDL.Null,
  'manual' : IDL.Null,
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'accuracy' : IDL.Float64,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PotholeType = IDL.Variant({
  'deep' : IDL.Null,
  'edge' : IDL.Null,
  'pavement' : IDL.Null,
  'complex' : IDL.Null,
  'rough_size' : IDL.Null,
  'surface_cracks' : IDL.Null,
  'unknown' : IDL.Null,
});
export const PotholeDetails = IDL.Record({
  'potholeType' : PotholeType,
  'image_url' : IDL.Text,
  'distance_from_vehicle' : IDL.Float64,
  'createdAt' : Time,
  'size' : IDL.Float64,
  'severity' : IDL.Text,
  'depth' : IDL.Float64,
  'location' : IDL.Record({
    'coordinates' : IDL.Tuple(IDL.Float64, IDL.Float64),
    'accuracy' : IDL.Float64,
  }),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AccidentRecord = IDL.Record({
  'id' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
  'location' : Location,
  'detectionMethod' : DetectionMethod,
  'analysisResults' : IDL.Opt(IDL.Text),
  'images' : IDL.Vec(ExternalBlob),
});
export const MotionType = IDL.Variant({
  'static' : IDL.Null,
  'moving' : IDL.Null,
});
export const ObjectType = IDL.Variant({
  'pedestrian' : IDL.Null,
  'debris' : IDL.Null,
  'vehicle' : IDL.Null,
  'unknown' : IDL.Null,
});
export const Classification = IDL.Record({
  'motion' : MotionType,
  'objectType' : ObjectType,
});
export const ObstacleEvent = IDL.Record({
  'id' : IDL.Text,
  'type' : IDL.Text,
  'confidenceLevel' : IDL.Float64,
  'timestamp' : Time,
  'associatedDetectionId' : IDL.Text,
  'image' : ExternalBlob,
  'position' : IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 }),
  'riskLevel' : IDL.Record({ 'description' : IDL.Text, 'level' : IDL.Text }),
  'potholeDetails' : IDL.Opt(PotholeDetails),
  'classification' : Classification,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAccidentRecord' : IDL.Func(
      [
        IDL.Text,
        DetectionMethod,
        Location,
        Time,
        IDL.Vec(ExternalBlob),
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'addPotholeSpecificEvent' : IDL.Func(
      [
        IDL.Text,
        IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 }),
        IDL.Float64,
        Time,
        IDL.Text,
        ExternalBlob,
        IDL.Record({ 'description' : IDL.Text, 'level' : IDL.Text }),
        PotholeDetails,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAccidentRecord' : IDL.Func([IDL.Text], [AccidentRecord], ['query']),
  'getAllAccidentRecords' : IDL.Func([], [IDL.Vec(AccidentRecord)], ['query']),
  'getAllObstacleEvents' : IDL.Func([], [IDL.Vec(ObstacleEvent)], ['query']),
  'getAllPotholeEvents' : IDL.Func([], [IDL.Vec(ObstacleEvent)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getObstacleEvent' : IDL.Func([IDL.Text], [ObstacleEvent], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'storeObstacleEvent' : IDL.Func(
      [
        IDL.Text,
        IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 }),
        IDL.Text,
        IDL.Float64,
        Time,
        IDL.Text,
        ExternalBlob,
        IDL.Record({ 'description' : IDL.Text, 'level' : IDL.Text }),
        Classification,
        IDL.Opt(PotholeDetails),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const DetectionMethod = IDL.Variant({
    'aiAnalyzed' : IDL.Null,
    'manual' : IDL.Null,
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'accuracy' : IDL.Float64,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PotholeType = IDL.Variant({
    'deep' : IDL.Null,
    'edge' : IDL.Null,
    'pavement' : IDL.Null,
    'complex' : IDL.Null,
    'rough_size' : IDL.Null,
    'surface_cracks' : IDL.Null,
    'unknown' : IDL.Null,
  });
  const PotholeDetails = IDL.Record({
    'potholeType' : PotholeType,
    'image_url' : IDL.Text,
    'distance_from_vehicle' : IDL.Float64,
    'createdAt' : Time,
    'size' : IDL.Float64,
    'severity' : IDL.Text,
    'depth' : IDL.Float64,
    'location' : IDL.Record({
      'coordinates' : IDL.Tuple(IDL.Float64, IDL.Float64),
      'accuracy' : IDL.Float64,
    }),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AccidentRecord = IDL.Record({
    'id' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
    'location' : Location,
    'detectionMethod' : DetectionMethod,
    'analysisResults' : IDL.Opt(IDL.Text),
    'images' : IDL.Vec(ExternalBlob),
  });
  const MotionType = IDL.Variant({ 'static' : IDL.Null, 'moving' : IDL.Null });
  const ObjectType = IDL.Variant({
    'pedestrian' : IDL.Null,
    'debris' : IDL.Null,
    'vehicle' : IDL.Null,
    'unknown' : IDL.Null,
  });
  const Classification = IDL.Record({
    'motion' : MotionType,
    'objectType' : ObjectType,
  });
  const ObstacleEvent = IDL.Record({
    'id' : IDL.Text,
    'type' : IDL.Text,
    'confidenceLevel' : IDL.Float64,
    'timestamp' : Time,
    'associatedDetectionId' : IDL.Text,
    'image' : ExternalBlob,
    'position' : IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 }),
    'riskLevel' : IDL.Record({ 'description' : IDL.Text, 'level' : IDL.Text }),
    'potholeDetails' : IDL.Opt(PotholeDetails),
    'classification' : Classification,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAccidentRecord' : IDL.Func(
        [
          IDL.Text,
          DetectionMethod,
          Location,
          Time,
          IDL.Vec(ExternalBlob),
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'addPotholeSpecificEvent' : IDL.Func(
        [
          IDL.Text,
          IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 }),
          IDL.Float64,
          Time,
          IDL.Text,
          ExternalBlob,
          IDL.Record({ 'description' : IDL.Text, 'level' : IDL.Text }),
          PotholeDetails,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAccidentRecord' : IDL.Func([IDL.Text], [AccidentRecord], ['query']),
    'getAllAccidentRecords' : IDL.Func(
        [],
        [IDL.Vec(AccidentRecord)],
        ['query'],
      ),
    'getAllObstacleEvents' : IDL.Func([], [IDL.Vec(ObstacleEvent)], ['query']),
    'getAllPotholeEvents' : IDL.Func([], [IDL.Vec(ObstacleEvent)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getObstacleEvent' : IDL.Func([IDL.Text], [ObstacleEvent], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'storeObstacleEvent' : IDL.Func(
        [
          IDL.Text,
          IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 }),
          IDL.Text,
          IDL.Float64,
          Time,
          IDL.Text,
          ExternalBlob,
          IDL.Record({ 'description' : IDL.Text, 'level' : IDL.Text }),
          Classification,
          IDL.Opt(PotholeDetails),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };