/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ObstacleEvent {
    id: string;
    type: string;
    confidenceLevel: number;
    timestamp: Time;
    associatedDetectionId: string;
    image: ExternalBlob;
    position: {
        x: number;
        y: number;
    };
    riskLevel: {
        description: string;
        level: string;
    };
    potholeDetails?: PotholeDetails;
    classification: Classification;
}
export type Time = bigint;
export interface Classification {
    motion: MotionType;
    objectType: ObjectType;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PotholeDetails {
    potholeType: PotholeType;
    image_url: string;
    distance_from_vehicle: number;
    createdAt: Time;
    size: number;
    severity: string;
    depth: number;
    location: {
        coordinates: [number, number];
        accuracy: number;
    };
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum MotionType {
    static_ = "static",
    moving = "moving"
}
export enum ObjectType {
    pedestrian = "pedestrian",
    debris = "debris",
    vehicle = "vehicle",
    unknown_ = "unknown"
}
export enum PotholeType {
    deep = "deep",
    edge = "edge",
    pavement = "pavement",
    complex = "complex",
    rough_size = "rough_size",
    surface_cracks = "surface_cracks",
    unknown_ = "unknown"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPotholeSpecificEvent(id: string, position: {
        x: number;
        y: number;
    }, confidenceLevel: number, timestamp: Time, associatedDetectionId: string, image: ExternalBlob, riskLevel: {
        description: string;
        level: string;
    }, potholeDetails: PotholeDetails): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllObstacleEvents(): Promise<Array<ObstacleEvent>>;
    getAllPotholeEvents(): Promise<Array<ObstacleEvent>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getObstacleEvent(id: string): Promise<ObstacleEvent>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    storeObstacleEvent(id: string, position: {
        x: number;
        y: number;
    }, type: string, confidenceLevel: number, timestamp: Time, associatedDetectionId: string, image: ExternalBlob, riskLevel: {
        description: string;
        level: string;
    }, classification: Classification, potholeDetails: PotholeDetails | null): Promise<void>;
}
import type { Classification as _Classification, ExternalBlob as _ExternalBlob, MotionType as _MotionType, ObjectType as _ObjectType, ObstacleEvent as _ObstacleEvent, PotholeDetails as _PotholeDetails, PotholeType as _PotholeType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPotholeSpecificEvent(arg0: string, arg1: {
        x: number;
        y: number;
    }, arg2: number, arg3: Time, arg4: string, arg5: ExternalBlob, arg6: {
        description: string;
        level: string;
    }, arg7: PotholeDetails): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPotholeSpecificEvent(arg0, arg1, arg2, arg3, arg4, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_PotholeDetails_n9(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPotholeSpecificEvent(arg0, arg1, arg2, arg3, arg4, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_PotholeDetails_n9(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllObstacleEvents(): Promise<Array<ObstacleEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllObstacleEvents();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllObstacleEvents();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPotholeEvents(): Promise<Array<ObstacleEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPotholeEvents();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPotholeEvents();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getObstacleEvent(arg0: string): Promise<ObstacleEvent> {
        if (this.processError) {
            try {
                const result = await this.actor.getObstacleEvent(arg0);
                return from_candid_ObstacleEvent_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getObstacleEvent(arg0);
            return from_candid_ObstacleEvent_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async storeObstacleEvent(arg0: string, arg1: {
        x: number;
        y: number;
    }, arg2: string, arg3: number, arg4: Time, arg5: string, arg6: ExternalBlob, arg7: {
        description: string;
        level: string;
    }, arg8: Classification, arg9: PotholeDetails | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeObstacleEvent(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg6), arg7, to_candid_Classification_n33(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg9));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeObstacleEvent(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg6), arg7, to_candid_Classification_n33(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg9));
            return result;
        }
    }
}
function from_candid_Classification_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Classification): Classification {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_MotionType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MotionType): MotionType {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_ObjectType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ObjectType): ObjectType {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
async function from_candid_ObstacleEvent_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ObstacleEvent): Promise<ObstacleEvent> {
    return await from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_PotholeDetails_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PotholeDetails): PotholeDetails {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_PotholeType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PotholeType): PotholeType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PotholeDetails]): PotholeDetails | null {
    return value.length === 0 ? null : from_candid_PotholeDetails_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    type: string;
    confidenceLevel: number;
    timestamp: _Time;
    associatedDetectionId: string;
    image: _ExternalBlob;
    position: {
        x: number;
        y: number;
    };
    riskLevel: {
        description: string;
        level: string;
    };
    potholeDetails: [] | [_PotholeDetails];
    classification: _Classification;
}): Promise<{
    id: string;
    type: string;
    confidenceLevel: number;
    timestamp: Time;
    associatedDetectionId: string;
    image: ExternalBlob;
    position: {
        x: number;
        y: number;
    };
    riskLevel: {
        description: string;
        level: string;
    };
    potholeDetails?: PotholeDetails;
    classification: Classification;
}> {
    return {
        id: value.id,
        type: value.type,
        confidenceLevel: value.confidenceLevel,
        timestamp: value.timestamp,
        associatedDetectionId: value.associatedDetectionId,
        image: await from_candid_ExternalBlob_n18(_uploadFile, _downloadFile, value.image),
        position: value.position,
        riskLevel: value.riskLevel,
        potholeDetails: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.potholeDetails)),
        classification: from_candid_Classification_n24(_uploadFile, _downloadFile, value.classification)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    potholeType: _PotholeType;
    image_url: string;
    distance_from_vehicle: number;
    createdAt: _Time;
    size: number;
    severity: string;
    depth: number;
    location: {
        coordinates: [number, number];
        accuracy: number;
    };
}): {
    potholeType: PotholeType;
    image_url: string;
    distance_from_vehicle: number;
    createdAt: Time;
    size: number;
    severity: string;
    depth: number;
    location: {
        coordinates: [number, number];
        accuracy: number;
    };
} {
    return {
        potholeType: from_candid_PotholeType_n22(_uploadFile, _downloadFile, value.potholeType),
        image_url: value.image_url,
        distance_from_vehicle: value.distance_from_vehicle,
        createdAt: value.createdAt,
        size: value.size,
        severity: value.severity,
        depth: value.depth,
        location: value.location
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    motion: _MotionType;
    objectType: _ObjectType;
}): {
    motion: MotionType;
    objectType: ObjectType;
} {
    return {
        motion: from_candid_MotionType_n26(_uploadFile, _downloadFile, value.motion),
        objectType: from_candid_ObjectType_n28(_uploadFile, _downloadFile, value.objectType)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deep: null;
} | {
    edge: null;
} | {
    pavement: null;
} | {
    complex: null;
} | {
    rough_size: null;
} | {
    surface_cracks: null;
} | {
    unknown: null;
}): PotholeType {
    return "deep" in value ? PotholeType.deep : "edge" in value ? PotholeType.edge : "pavement" in value ? PotholeType.pavement : "complex" in value ? PotholeType.complex : "rough_size" in value ? PotholeType.rough_size : "surface_cracks" in value ? PotholeType.surface_cracks : "unknown" in value ? PotholeType.unknown : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    static: null;
} | {
    moving: null;
}): MotionType {
    return "static" in value ? MotionType.static : "moving" in value ? MotionType.moving : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pedestrian: null;
} | {
    debris: null;
} | {
    vehicle: null;
} | {
    unknown: null;
}): ObjectType {
    return "pedestrian" in value ? ObjectType.pedestrian : "debris" in value ? ObjectType.debris : "vehicle" in value ? ObjectType.vehicle : "unknown" in value ? ObjectType.unknown : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ObstacleEvent>): Promise<Array<ObstacleEvent>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ObstacleEvent_n16(_uploadFile, _downloadFile, x)));
}
function to_candid_Classification_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Classification): _Classification {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_MotionType_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MotionType): _MotionType {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_ObjectType_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ObjectType): _ObjectType {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_PotholeDetails_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PotholeDetails): _PotholeDetails {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_PotholeType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PotholeType): _PotholeType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PotholeDetails | null): [] | [_PotholeDetails] {
    return value === null ? candid_none() : candid_some(to_candid_PotholeDetails_n9(_uploadFile, _downloadFile, value));
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    potholeType: PotholeType;
    image_url: string;
    distance_from_vehicle: number;
    createdAt: Time;
    size: number;
    severity: string;
    depth: number;
    location: {
        coordinates: [number, number];
        accuracy: number;
    };
}): {
    potholeType: _PotholeType;
    image_url: string;
    distance_from_vehicle: number;
    createdAt: _Time;
    size: number;
    severity: string;
    depth: number;
    location: {
        coordinates: [number, number];
        accuracy: number;
    };
} {
    return {
        potholeType: to_candid_PotholeType_n11(_uploadFile, _downloadFile, value.potholeType),
        image_url: value.image_url,
        distance_from_vehicle: value.distance_from_vehicle,
        createdAt: value.createdAt,
        size: value.size,
        severity: value.severity,
        depth: value.depth,
        location: value.location
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    motion: MotionType;
    objectType: ObjectType;
}): {
    motion: _MotionType;
    objectType: _ObjectType;
} {
    return {
        motion: to_candid_MotionType_n35(_uploadFile, _downloadFile, value.motion),
        objectType: to_candid_ObjectType_n37(_uploadFile, _downloadFile, value.objectType)
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PotholeType): {
    deep: null;
} | {
    edge: null;
} | {
    pavement: null;
} | {
    complex: null;
} | {
    rough_size: null;
} | {
    surface_cracks: null;
} | {
    unknown: null;
} {
    return value == PotholeType.deep ? {
        deep: null
    } : value == PotholeType.edge ? {
        edge: null
    } : value == PotholeType.pavement ? {
        pavement: null
    } : value == PotholeType.complex ? {
        complex: null
    } : value == PotholeType.rough_size ? {
        rough_size: null
    } : value == PotholeType.surface_cracks ? {
        surface_cracks: null
    } : value == PotholeType.unknown ? {
        unknown_: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MotionType): {
    static: null;
} | {
    moving: null;
} {
    return value == MotionType.static ? {
        static_: null
    } : value == MotionType.moving ? {
        moving: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ObjectType): {
    pedestrian: null;
} | {
    debris: null;
} | {
    vehicle: null;
} | {
    unknown: null;
} {
    return value == ObjectType.pedestrian ? {
        pedestrian: null
    } : value == ObjectType.debris ? {
        debris: null
    } : value == ObjectType.vehicle ? {
        vehicle: null
    } : value == ObjectType.unknown ? {
        unknown_: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
