/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ObstacleEvent {
    id: string;
    type: string;
    confidenceLevel: number;
    timestamp: Time;
    associatedDetectionId: string;
    image: ExternalBlob;
    position: {
        x: number;
        y: number;
    };
    riskLevel: {
        description: string;
        level: string;
    };
}
export interface VideoProcessingStatusResponse {
}
export type Time = bigint;
export interface EmergencyEvent {
    id: string;
    type: string;
    resolutionStatus: string;
    description: string;
    timestamp: Time;
    associatedDetectionId: string;
    severity: {
        urgency: string;
        level: string;
    };
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface SpecificationReportResponse {
    id: string;
    content: ExternalBlob;
    createdAt: Time;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DetectionResult {
    id: string;
    environmentalConditions: {
        roadType: string;
        surfaceType: string;
        lighting: string;
        weather: string;
    };
    metrics: {
        objectDetection: string;
        systemPerformance: {
            cpuUtilization: number;
            gpuUtilization: number;
            memoryUsage: number;
            hardwareType: string;
        };
        detectionQuality: number;
        frameRate: number;
    };
    processingTime: bigint;
    confidenceScore: number;
    processedImage: ExternalBlob;
    timestamp: Time;
    image: ExternalBlob;
}
export interface SpeedLimitDetection {
    id: string;
    frameData: ExternalBlob;
    confidenceLevel: number;
    timestamp: Time;
    detectedSpeedLimit?: bigint;
    associatedDetectionId: string;
}
export interface CameraStatusRequest {
    state: string;
}
export interface VideoUploadResponse {
    taskId: string;
}
export interface VideoUploadRequest {
    videoBlob: ExternalBlob;
}
export interface HardwarePerformanceMetrics {
    optimizationLevel: string;
    processingEfficiency: number;
    cpuUtilization: number;
    gpuUtilization: number;
    memoryUsage: number;
    benchmarkScores: {
        gpuScore: number;
        cpuScore: number;
    };
    hardwareType: string;
}
export interface VideoProcessingStatusRequest {
    taskId: string;
}
export interface CameraStatusResponse {
    message: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    getAllDetectionResults(): Promise<Array<DetectionResult>>;
    getAllEmergencyEvents(): Promise<Array<EmergencyEvent>>;
    getAllHardwarePerformanceMetrics(): Promise<Array<HardwarePerformanceMetrics>>;
    getAllObstacleEvents(): Promise<Array<ObstacleEvent>>;
    getAllSpecificationReports(): Promise<Array<SpecificationReportResponse>>;
    getAllSpeedLimitDetections(): Promise<Array<SpeedLimitDetection>>;
    getCombinedAlertHistory(): Promise<{
        detectionResults: Array<DetectionResult>;
        speedLimitDetections: Array<SpeedLimitDetection>;
        emergencyEvents: Array<EmergencyEvent>;
        hardwarePerformanceMetrics: Array<HardwarePerformanceMetrics>;
        obstacleEvents: Array<ObstacleEvent>;
    }>;
    getDetectionResult(id: string): Promise<DetectionResult>;
    getDetectionStatistics(): Promise<{
        totalDetections: bigint;
        totalHighRiskEvents: bigint;
        averageDetectionTime: number;
        highestRiskLevel: string;
        totalSpeedLimitDetections: bigint;
        totalEmergencyEvents: bigint;
        mostCommonObjectType: string;
        totalObstacleEvents: bigint;
        averageConfidenceScore: number;
        averageHardwareEfficiency: number;
        averageSpeedLimitConfidence: number;
        averageProcessingTime: number;
    }>;
    getEmergencyEvent(id: string): Promise<EmergencyEvent>;
    getEnvironmentalAnalysis(): Promise<{
        detectionScoreByCondition: {
            surfaceQuality: string;
            avgScore: number;
            commonRoadType: string;
            lighting: string;
            weather: string;
        };
    }>;
    getFilteredAlertHistory(filter: {
        detectionRange?: number;
        weatherCondition?: string;
        timeRange?: {
            end: Time;
            start: Time;
        };
        severity?: string;
        speedLimitRange?: {
            lower: bigint;
            upper: bigint;
        };
        objectType?: string;
        riskLevel?: string;
    }): Promise<{
        detectionResults: Array<DetectionResult>;
        speedLimitDetections: Array<SpeedLimitDetection>;
        emergencyEvents: Array<EmergencyEvent>;
        obstacleEvents: Array<ObstacleEvent>;
    }>;
    getFilteredEventHistory(filter: {
        detectionRange?: number;
        severity?: string;
        objectType?: string;
        riskLevel?: string;
    }): Promise<{
        emergencyEvents: Array<EmergencyEvent>;
        obstacleEvents: Array<ObstacleEvent>;
    }>;
    getHardwarePerformanceMetrics(id: string): Promise<HardwarePerformanceMetrics>;
    getObstacleEvent(id: string): Promise<ObstacleEvent>;
    getSpecificationReport(id: string): Promise<SpecificationReportResponse>;
    getSpeedLimitDetection(id: string): Promise<SpeedLimitDetection>;
    getVideoProcessingStatus(arg0: VideoProcessingStatusRequest): Promise<VideoProcessingStatusResponse>;
    handleVideoUpload(arg0: VideoUploadRequest): Promise<VideoUploadResponse>;
    storeDetectionResult(id: string, image: ExternalBlob, processedImage: ExternalBlob, confidenceScore: number, processingTime: bigint, timestamp: Time, lighting: string, weather: string, roadType: string, surfaceType: string, frameRate: number, detectionQuality: number, objectDetection: string, hardwareType: string, cpuUtilization: number, gpuUtilization: number, memoryUsage: number): Promise<void>;
    storeEmergencyEvent(id: string, type: string, timestamp: Time, associatedDetectionId: string, description: string, severity: {
        urgency: string;
        level: string;
    }, resolutionStatus: string): Promise<void>;
    storeHardwarePerformanceMetrics(id: string, hardwareType: string, cpuUtilization: number, gpuUtilization: number, memoryUsage: number, cpuScore: number, gpuScore: number, optimizationLevel: string, processingEfficiency: number): Promise<void>;
    storeObstacleEvent(id: string, position: {
        x: number;
        y: number;
    }, type: string, confidenceLevel: number, timestamp: Time, associatedDetectionId: string, image: ExternalBlob, riskLevel: {
        description: string;
        level: string;
    }): Promise<void>;
    storeSpecificationReport(id: string, content: ExternalBlob, createdAt: Time): Promise<void>;
    storeSpeedLimitDetection(id: string, detectedSpeedLimit: bigint | null, confidenceLevel: number, timestamp: Time, associatedDetectionId: string, frameData: ExternalBlob): Promise<void>;
    updateCameraStatus(arg0: CameraStatusRequest): Promise<CameraStatusResponse>;
}
import type { DetectionResult as _DetectionResult, EmergencyEvent as _EmergencyEvent, ExternalBlob as _ExternalBlob, HardwarePerformanceMetrics as _HardwarePerformanceMetrics, ObstacleEvent as _ObstacleEvent, SpecificationReportResponse as _SpecificationReportResponse, SpeedLimitDetection as _SpeedLimitDetection, Time as _Time, VideoUploadRequest as _VideoUploadRequest, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async getAllDetectionResults(): Promise<Array<DetectionResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDetectionResults();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDetectionResults();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEmergencyEvents(): Promise<Array<EmergencyEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmergencyEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmergencyEvents();
            return result;
        }
    }
    async getAllHardwarePerformanceMetrics(): Promise<Array<HardwarePerformanceMetrics>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHardwarePerformanceMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHardwarePerformanceMetrics();
            return result;
        }
    }
    async getAllObstacleEvents(): Promise<Array<ObstacleEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllObstacleEvents();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllObstacleEvents();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSpecificationReports(): Promise<Array<SpecificationReportResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSpecificationReports();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSpecificationReports();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSpeedLimitDetections(): Promise<Array<SpeedLimitDetection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSpeedLimitDetections();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSpeedLimitDetections();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCombinedAlertHistory(): Promise<{
        detectionResults: Array<DetectionResult>;
        speedLimitDetections: Array<SpeedLimitDetection>;
        emergencyEvents: Array<EmergencyEvent>;
        hardwarePerformanceMetrics: Array<HardwarePerformanceMetrics>;
        obstacleEvents: Array<ObstacleEvent>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCombinedAlertHistory();
                return from_candid_record_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCombinedAlertHistory();
            return from_candid_record_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDetectionResult(arg0: string): Promise<DetectionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getDetectionResult(arg0);
                return from_candid_DetectionResult_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDetectionResult(arg0);
            return from_candid_DetectionResult_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDetectionStatistics(): Promise<{
        totalDetections: bigint;
        totalHighRiskEvents: bigint;
        averageDetectionTime: number;
        highestRiskLevel: string;
        totalSpeedLimitDetections: bigint;
        totalEmergencyEvents: bigint;
        mostCommonObjectType: string;
        totalObstacleEvents: bigint;
        averageConfidenceScore: number;
        averageHardwareEfficiency: number;
        averageSpeedLimitConfidence: number;
        averageProcessingTime: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDetectionStatistics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDetectionStatistics();
            return result;
        }
    }
    async getEmergencyEvent(arg0: string): Promise<EmergencyEvent> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmergencyEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmergencyEvent(arg0);
            return result;
        }
    }
    async getEnvironmentalAnalysis(): Promise<{
        detectionScoreByCondition: {
            surfaceQuality: string;
            avgScore: number;
            commonRoadType: string;
            lighting: string;
            weather: string;
        };
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnvironmentalAnalysis();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnvironmentalAnalysis();
            return result;
        }
    }
    async getFilteredAlertHistory(arg0: {
        detectionRange?: number;
        weatherCondition?: string;
        timeRange?: {
            end: Time;
            start: Time;
        };
        severity?: string;
        speedLimitRange?: {
            lower: bigint;
            upper: bigint;
        };
        objectType?: string;
        riskLevel?: string;
    }): Promise<{
        detectionResults: Array<DetectionResult>;
        speedLimitDetections: Array<SpeedLimitDetection>;
        emergencyEvents: Array<EmergencyEvent>;
        obstacleEvents: Array<ObstacleEvent>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilteredAlertHistory(to_candid_record_n22(this._uploadFile, this._downloadFile, arg0));
                return from_candid_record_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilteredAlertHistory(to_candid_record_n22(this._uploadFile, this._downloadFile, arg0));
            return from_candid_record_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFilteredEventHistory(arg0: {
        detectionRange?: number;
        severity?: string;
        objectType?: string;
        riskLevel?: string;
    }): Promise<{
        emergencyEvents: Array<EmergencyEvent>;
        obstacleEvents: Array<ObstacleEvent>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilteredEventHistory(to_candid_record_n24(this._uploadFile, this._downloadFile, arg0));
                return from_candid_record_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilteredEventHistory(to_candid_record_n24(this._uploadFile, this._downloadFile, arg0));
            return from_candid_record_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHardwarePerformanceMetrics(arg0: string): Promise<HardwarePerformanceMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getHardwarePerformanceMetrics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHardwarePerformanceMetrics(arg0);
            return result;
        }
    }
    async getObstacleEvent(arg0: string): Promise<ObstacleEvent> {
        if (this.processError) {
            try {
                const result = await this.actor.getObstacleEvent(arg0);
                return from_candid_ObstacleEvent_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getObstacleEvent(arg0);
            return from_candid_ObstacleEvent_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSpecificationReport(arg0: string): Promise<SpecificationReportResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpecificationReport(arg0);
                return from_candid_SpecificationReportResponse_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpecificationReport(arg0);
            return from_candid_SpecificationReportResponse_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSpeedLimitDetection(arg0: string): Promise<SpeedLimitDetection> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpeedLimitDetection(arg0);
                return from_candid_SpeedLimitDetection_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpeedLimitDetection(arg0);
            return from_candid_SpeedLimitDetection_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoProcessingStatus(arg0: VideoProcessingStatusRequest): Promise<VideoProcessingStatusResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoProcessingStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoProcessingStatus(arg0);
            return result;
        }
    }
    async handleVideoUpload(arg0: VideoUploadRequest): Promise<VideoUploadResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.handleVideoUpload(await to_candid_VideoUploadRequest_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.handleVideoUpload(await to_candid_VideoUploadRequest_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async storeDetectionResult(arg0: string, arg1: ExternalBlob, arg2: ExternalBlob, arg3: number, arg4: bigint, arg5: Time, arg6: string, arg7: string, arg8: string, arg9: string, arg10: number, arg11: number, arg12: string, arg13: string, arg14: number, arg15: number, arg16: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeDetectionResult(arg0, await to_candid_ExternalBlob_n28(this._uploadFile, this._downloadFile, arg1), await to_candid_ExternalBlob_n28(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeDetectionResult(arg0, await to_candid_ExternalBlob_n28(this._uploadFile, this._downloadFile, arg1), await to_candid_ExternalBlob_n28(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16);
            return result;
        }
    }
    async storeEmergencyEvent(arg0: string, arg1: string, arg2: Time, arg3: string, arg4: string, arg5: {
        urgency: string;
        level: string;
    }, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeEmergencyEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeEmergencyEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async storeHardwarePerformanceMetrics(arg0: string, arg1: string, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: string, arg8: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeHardwarePerformanceMetrics(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeHardwarePerformanceMetrics(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async storeObstacleEvent(arg0: string, arg1: {
        x: number;
        y: number;
    }, arg2: string, arg3: number, arg4: Time, arg5: string, arg6: ExternalBlob, arg7: {
        description: string;
        level: string;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeObstacleEvent(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_ExternalBlob_n28(this._uploadFile, this._downloadFile, arg6), arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeObstacleEvent(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_ExternalBlob_n28(this._uploadFile, this._downloadFile, arg6), arg7);
            return result;
        }
    }
    async storeSpecificationReport(arg0: string, arg1: ExternalBlob, arg2: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeSpecificationReport(arg0, await to_candid_ExternalBlob_n28(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeSpecificationReport(arg0, await to_candid_ExternalBlob_n28(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async storeSpeedLimitDetection(arg0: string, arg1: bigint | null, arg2: number, arg3: Time, arg4: string, arg5: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeSpeedLimitDetection(arg0, to_candid_opt_n29(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, await to_candid_ExternalBlob_n28(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeSpeedLimitDetection(arg0, to_candid_opt_n29(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, await to_candid_ExternalBlob_n28(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateCameraStatus(arg0: CameraStatusRequest): Promise<CameraStatusResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCameraStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCameraStatus(arg0);
            return result;
        }
    }
}
async function from_candid_DetectionResult_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DetectionResult): Promise<DetectionResult> {
    return await from_candid_record_n10(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_ObstacleEvent_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ObstacleEvent): Promise<ObstacleEvent> {
    return await from_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function from_candid_SpecificationReportResponse_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SpecificationReportResponse): Promise<SpecificationReportResponse> {
    return await from_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_SpeedLimitDetection_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SpeedLimitDetection): Promise<SpeedLimitDetection> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    environmentalConditions: {
        roadType: string;
        surfaceType: string;
        lighting: string;
        weather: string;
    };
    metrics: {
        objectDetection: string;
        systemPerformance: {
            cpuUtilization: number;
            gpuUtilization: number;
            memoryUsage: number;
            hardwareType: string;
        };
        detectionQuality: number;
        frameRate: number;
    };
    processingTime: bigint;
    confidenceScore: number;
    processedImage: _ExternalBlob;
    timestamp: _Time;
    image: _ExternalBlob;
}): Promise<{
    id: string;
    environmentalConditions: {
        roadType: string;
        surfaceType: string;
        lighting: string;
        weather: string;
    };
    metrics: {
        objectDetection: string;
        systemPerformance: {
            cpuUtilization: number;
            gpuUtilization: number;
            memoryUsage: number;
            hardwareType: string;
        };
        detectionQuality: number;
        frameRate: number;
    };
    processingTime: bigint;
    confidenceScore: number;
    processedImage: ExternalBlob;
    timestamp: Time;
    image: ExternalBlob;
}> {
    return {
        id: value.id,
        environmentalConditions: value.environmentalConditions,
        metrics: value.metrics,
        processingTime: value.processingTime,
        confidenceScore: value.confidenceScore,
        processedImage: await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.processedImage),
        timestamp: value.timestamp,
        image: await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.image)
    };
}
async function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    type: string;
    confidenceLevel: number;
    timestamp: _Time;
    associatedDetectionId: string;
    image: _ExternalBlob;
    position: {
        x: number;
        y: number;
    };
    riskLevel: {
        description: string;
        level: string;
    };
}): Promise<{
    id: string;
    type: string;
    confidenceLevel: number;
    timestamp: Time;
    associatedDetectionId: string;
    image: ExternalBlob;
    position: {
        x: number;
        y: number;
    };
    riskLevel: {
        description: string;
        level: string;
    };
}> {
    return {
        id: value.id,
        type: value.type,
        confidenceLevel: value.confidenceLevel,
        timestamp: value.timestamp,
        associatedDetectionId: value.associatedDetectionId,
        image: await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.image),
        position: value.position,
        riskLevel: value.riskLevel
    };
}
async function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: _ExternalBlob;
    createdAt: _Time;
}): Promise<{
    id: string;
    content: ExternalBlob;
    createdAt: Time;
}> {
    return {
        id: value.id,
        content: await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.content),
        createdAt: value.createdAt
    };
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    frameData: _ExternalBlob;
    confidenceLevel: number;
    timestamp: _Time;
    detectedSpeedLimit: [] | [bigint];
    associatedDetectionId: string;
}): Promise<{
    id: string;
    frameData: ExternalBlob;
    confidenceLevel: number;
    timestamp: Time;
    detectedSpeedLimit?: bigint;
    associatedDetectionId: string;
}> {
    return {
        id: value.id,
        frameData: await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.frameData),
        confidenceLevel: value.confidenceLevel,
        timestamp: value.timestamp,
        detectedSpeedLimit: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.detectedSpeedLimit)),
        associatedDetectionId: value.associatedDetectionId
    };
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    detectionResults: Array<_DetectionResult>;
    speedLimitDetections: Array<_SpeedLimitDetection>;
    emergencyEvents: Array<_EmergencyEvent>;
    hardwarePerformanceMetrics: Array<_HardwarePerformanceMetrics>;
    obstacleEvents: Array<_ObstacleEvent>;
}): Promise<{
    detectionResults: Array<DetectionResult>;
    speedLimitDetections: Array<SpeedLimitDetection>;
    emergencyEvents: Array<EmergencyEvent>;
    hardwarePerformanceMetrics: Array<HardwarePerformanceMetrics>;
    obstacleEvents: Array<ObstacleEvent>;
}> {
    return {
        detectionResults: await from_candid_vec_n8(_uploadFile, _downloadFile, value.detectionResults),
        speedLimitDetections: await from_candid_vec_n18(_uploadFile, _downloadFile, value.speedLimitDetections),
        emergencyEvents: value.emergencyEvents,
        hardwarePerformanceMetrics: value.hardwarePerformanceMetrics,
        obstacleEvents: await from_candid_vec_n12(_uploadFile, _downloadFile, value.obstacleEvents)
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    detectionResults: Array<_DetectionResult>;
    speedLimitDetections: Array<_SpeedLimitDetection>;
    emergencyEvents: Array<_EmergencyEvent>;
    obstacleEvents: Array<_ObstacleEvent>;
}): Promise<{
    detectionResults: Array<DetectionResult>;
    speedLimitDetections: Array<SpeedLimitDetection>;
    emergencyEvents: Array<EmergencyEvent>;
    obstacleEvents: Array<ObstacleEvent>;
}> {
    return {
        detectionResults: await from_candid_vec_n8(_uploadFile, _downloadFile, value.detectionResults),
        speedLimitDetections: await from_candid_vec_n18(_uploadFile, _downloadFile, value.speedLimitDetections),
        emergencyEvents: value.emergencyEvents,
        obstacleEvents: await from_candid_vec_n12(_uploadFile, _downloadFile, value.obstacleEvents)
    };
}
async function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    emergencyEvents: Array<_EmergencyEvent>;
    obstacleEvents: Array<_ObstacleEvent>;
}): Promise<{
    emergencyEvents: Array<EmergencyEvent>;
    obstacleEvents: Array<ObstacleEvent>;
}> {
    return {
        emergencyEvents: value.emergencyEvents,
        obstacleEvents: await from_candid_vec_n12(_uploadFile, _downloadFile, value.obstacleEvents)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ObstacleEvent>): Promise<Array<ObstacleEvent>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ObstacleEvent_n13(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SpecificationReportResponse>): Promise<Array<SpecificationReportResponse>> {
    return await Promise.all(value.map(async (x)=>await from_candid_SpecificationReportResponse_n16(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SpeedLimitDetection>): Promise<Array<SpeedLimitDetection>> {
    return await Promise.all(value.map(async (x)=>await from_candid_SpeedLimitDetection_n19(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DetectionResult>): Promise<Array<DetectionResult>> {
    return await Promise.all(value.map(async (x)=>await from_candid_DetectionResult_n9(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_VideoUploadRequest_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoUploadRequest): Promise<_VideoUploadRequest> {
    return await to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    detectionRange?: number;
    weatherCondition?: string;
    timeRange?: {
        end: Time;
        start: Time;
    };
    severity?: string;
    speedLimitRange?: {
        lower: bigint;
        upper: bigint;
    };
    objectType?: string;
    riskLevel?: string;
}): {
    detectionRange: [] | [number];
    weatherCondition: [] | [string];
    timeRange: [] | [{
            end: _Time;
            start: _Time;
        }];
    severity: [] | [string];
    speedLimitRange: [] | [{
            lower: bigint;
            upper: bigint;
        }];
    objectType: [] | [string];
    riskLevel: [] | [string];
} {
    return {
        detectionRange: value.detectionRange ? candid_some(value.detectionRange) : candid_none(),
        weatherCondition: value.weatherCondition ? candid_some(value.weatherCondition) : candid_none(),
        timeRange: value.timeRange ? candid_some(value.timeRange) : candid_none(),
        severity: value.severity ? candid_some(value.severity) : candid_none(),
        speedLimitRange: value.speedLimitRange ? candid_some(value.speedLimitRange) : candid_none(),
        objectType: value.objectType ? candid_some(value.objectType) : candid_none(),
        riskLevel: value.riskLevel ? candid_some(value.riskLevel) : candid_none()
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    detectionRange?: number;
    severity?: string;
    objectType?: string;
    riskLevel?: string;
}): {
    detectionRange: [] | [number];
    severity: [] | [string];
    objectType: [] | [string];
    riskLevel: [] | [string];
} {
    return {
        detectionRange: value.detectionRange ? candid_some(value.detectionRange) : candid_none(),
        severity: value.severity ? candid_some(value.severity) : candid_none(),
        objectType: value.objectType ? candid_some(value.objectType) : candid_none(),
        riskLevel: value.riskLevel ? candid_some(value.riskLevel) : candid_none()
    };
}
async function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    videoBlob: ExternalBlob;
}): Promise<{
    videoBlob: _ExternalBlob;
}> {
    return {
        videoBlob: await to_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value.videoBlob)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
